import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from "react";
import Axios from 'axios'

export default function Nanny() {
const [name, setName] = useState('');
const [email, setEmail] = useState('');
const [photo, setPhoto] = useState('');
const [availability, setAvailability] = useState('');
const [phone, setPhone] = useState('');
const [venmoId, setVenmoId] = useState('');
const [emergencyContact, setEmergencyContact] = useState('');
const addNanny = () => {
  console.log(name,email,photo,availability);
  Axios.post ('http://localhost:3001/create',
  {
    name: name,
    email: email,
    photo: photo,
    availability: availability,
    phone:phone,
    venmoId:venmoId,
    emergencyContact:emergencyContact
  }
  ).then(() => {
    console.log('you have a new nanny')
  })
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Sophie's Portal
        </h1>

        <p className={styles.description}>
          A place for all things Sophie
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <div className='registration'>
            <h2>Registration</h2>
            <label>Name</label>
            <input type="text" onChange={(e) => {setName(e.target.value)}}/>
            <label>Email</label>
            <input type="text" onChange={(e) => {setEmail(e.target.value)}} /> 
            <label>Photo (url)</label>
            <input type="text" onChange={(e) => {setPhoto(e.target.value)}}/>
            <label>Availability</label>
            <input type="text" onChange={(e) => {setAvailability(e.target.value)}}/>
            <label>phone</label>
            <input type="text" onChange={(e) => {setPhone(e.target.value)}}/>
            <label>Venmo Id</label>
            <input type="text" onChange={(e) => {setVenmoId(e.target.value)}}/>
            <label>Emergency Contact</label>
            <input type="text" onChange={(e) => {setEmergencyContact(e.target.value)}}/>
            <button onClick={addNanny}>Add nanny</button>
            </div>
          </div>

          <div className={styles.card}>
            <div className='login'>
            <h2>Login</h2>
            <input type="text" placeholder='Username..'/>
            <input type="text" placeholder='Password..' />
            <button>Login</button>
            </div>
          </div>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
