
import { useState } from "react";
import Axios from 'axios'


export default function Register() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [status, setStatus] = useState('')

  const addNanny = (e) => {
    // e.preventDefault();
    // console.log(name,email);
    Axios.post('http://localhost:3001/create',
      {
        name: name,
        email: email,
        password: password
      }
    ).then((response) => {
      console.log('you have a new nanny');
      console.log(response);
    })
  }



  return (
    <div className='container'>
      <header>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </header>

      <main className='main'>
        <h1 className='title'>
          Welcome to Sophie's Portal
        </h1>

        <p className='description'>
          A place for all things Sophie
        </p>

        <div className='grid'>
          <div className='card'>
            <div className='registration'>
              <h2>Registration</h2>

              <label>name</label>

              <input
                type="text"
                onChange={(e) => {
                  setName(e.target.value);
                }} />
              <label>email</label>

              <input
                type="email"
                onChange={(e) => {
                  setEmail(e.target.value);
                }} />
              <label>Password</label>

              <input
                type="text"
                onChange={(e) => {
                  setPassword(e.target.value);
                }} />

              <label className="switch">

                <button
                  value={'parent'}
                  onClick={(e) => { setStatus(e.target.value) }}>
                  Parent
                </button>

                <button
                  value={'nanny'}
                  onClick={(e) => { setStatus(e.target.value) }}>
                  Nanny
                </button>
              </label>
              <button onClick={addNanny}>Register</button>
            </div>
          </div>

          <div className='card'>
            <div className='login'>
              <h2>Login</h2>
              <input type="text" placeholder='Username..' />
              <input type="text" placeholder='Password..' />
              <button>Login</button>
            </div>
          </div>

 
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className='logo'>

          </span>
        </a>
      </footer>
    </div>
  )
}